language: python
sudo: false
cache: pip
branches:
  only:
    - master

matrix:
  include:
    - env: TOXENV=py27-twlatest
      python: 2.7
    - env: TOXENV=py27-twlatest
      python: 2.7
    - env: TOXENV=py36-twlatest
      python: 3.6
    - env: TOXENV=py27-twtrunk
      python: 2.7
    - env: TOXENV=py27-twtrunk
      python: 2.7
    - env: TOXENV=pypy-twtrunk
      python: "pypy"
      dist: trusty
    - env: TOXENV=pypy-twlatest
      python: "pypy"
      dist: trusty
    - env: TOXENV=pypy-twlatest
      python: "pypy"
      dist: trusty
    - env: TOXENV=pypy-twtrunk
      python: "pypy"
      dist: trusty

script:
  - pip install tox codecov
  - tox

after_success:
  # Codecov needs combined coverage, and having the raw report in the test
  # output can be useful.
  - tox -e coverage-report
  - codecov

notifications:
  email: false
