language: python
sudo: false
cache: pip
branches:
  only:
    - master
python:
  - 2.7

matrix:
  include:
    - env: TOXENV=py27-twlatest OPENSSL_VERSION=1.0.2h
    - env: TOXENV=py27-twlatest
    - env: TOXENV=py36-twlatest
      python: 3.6
    - env: TOXENV=pypy-twlatest OPENSSL_VERSION=1.0.2h
    - env: TOXENV=pypy-twlatest
    - env: TOXENV=py27-tw14 OPENSSL_VERSION=1.0.2h
    - env: TOXENV=py27-tw14
    - env: TOXENV=pypy-tw14 OPENSSL_VERSION=1.0.2h
    - env: TOXENV=pypy-tw14
    - env: TOXENV=py27-twtrunk OPENSSL_VERSION=1.0.2h
    - env: TOXENV=py27-twtrunk
    - env: TOXENV=pypy-twtrunk OPENSSL_VERSION=1.0.2h
    - env: TOXENV=pypy-twtrunk

install:
  - "./.travis/install.sh"

script:
  - "./.travis/run.sh"

after_success:
  # Codecov needs combined coverage, and having the raw report in the test
  # output can be useful.
  - tox -e coverage-report
  - codecov

notifications:
  email: false
