language: python
sudo: false
cache: pip
branches:
  only:
    - master
python:
  - 2.7

env:
  - TOXENV=py27-twlatest OPENSSL_VERSION=1.0.2h
  - TOXENV=py27-twlatest
  - TOXENV=pypy-twlatest OPENSSL_VERSION=1.0.2h
  - TOXENV=pypy-twlatest
  - TOXENV=py27-tw14 OPENSSL_VERSION=1.0.2h
  - TOXENV=py27-tw14
  - TOXENV=pypy-tw14 OPENSSL_VERSION=1.0.2h
  - TOXENV=pypy-tw14
  - TOXENV=py27-twtrunk OPENSSL_VERSION=1.0.2h
  - TOXENV=py27-twtrunk
  - TOXENV=pypy-twtrunk OPENSSL_VERSION=1.0.2h
  - TOXENV=pypy-twtrunk

install:
  - "./.travis/install.sh"

script:
  - "./.travis/run.sh"

after_success:
  # Codecov needs combined coverage, and having the raw report in the test
  # output can be useful.
  - tox -e coverage-report
  - codecov

notifications:
  email: false
